config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(
                    Rails.root.join("config/routes/#{routes_name}.rb")
                  ))
  end
end

class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Hours::Application.routes.draw do
  if Hours.single_tenant_mode?
    root "projects#index"
    draw :subdomain_present
    draw :subdomain_blank
  else
    constraints(SubdomainPresent) do
      root "projects#index", as: :subdomain_root
      draw :subdomain_present
    end

    constraints(SubdomainBlank) do
      root to: "pages#show", id: "landing"
      draw :subdomain_blank
    end
  end
end

app/models/client.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: clients
#
#  id                :integer          not null, primary key
#  name              :string           default(""), not null
#  description       :string           default("")
#  logo_file_name    :string
#  logo_content_type :string
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#  created_at        :datetime
#  updated_at        :datetime
#

class Client < ApplicationRecord
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }
  scope :by_name, -> { order("lower(name)") }
  scope :by_last_updated, -> { order("clients.updated_at DESC") }
  has_many :projects

  has_many :hours, through: :projects
  has_many :mileages, through: :projects

  has_attached_file :logo,
                    styles: { original: "100x100#" },
                    default_url: "",
                    s3_protocol: ""
  validates_attachment_content_type :logo, content_type: %r{\Aimage/.*\Z}

  def logo_url
    logo.url(:original)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def show
    @projects = resource.projects.by_last_updated.page(params[:page]).per(3)
    @time_series = time_series_for(resource)
  end

  def index
    @client = Client.new
    @clients = Client.by_name
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path, notice: t(:client_created)
    else
      @clients = Client.by_name
      render "clients/index"
    end
  end

  def edit
    resource
  end

  def update
    if resource.update_attributes(client_params)
      redirect_to clients_path, notice: t(:client_updated)
    else
      render :edit
    end
  end

  private

  def resource
    @client ||= Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :description, :logo)
  end
end

app/views/clients/_client.html.haml
%li
  .client
    = link_to client_path(client) do
      = client_title(client)
    #{link_to t("client.edit"), edit_client_path(client), class: "edit"}

app/views/clients/_form.html.haml
= simple_form_for(@client) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, required: true, autofocus: true
    = f.input :description, required: false
    = f.input :logo, as: :file
    = f.button :submit

app/views/clients/_project.html.haml
- projects.each do |project|
  - localized_cache [project, current_locale] do
    - present project do |project_presenter|
      %li.container.project
        %h2.project-title
          = link_to project_path(project) do
            = project.name
        %ul.tags-list
          - project.tags.last(5).each do |tag|
            = link_to tag_path(tag) do
              %li.tag= tag.name
        %hr/
        .activities-overview
          %ol.activities
            = project_presenter.show_categories
        .bar
          .graph
            = project_presenter.show_categories_bar
        .activity-description
          - if project.users.count > 0
            = t(:project_activity_html, full_name: project.users.first.full_name, count: project.users.count, hours: EntryStats.new(project.hours).total_hours, project: project.name)
          - else
            = t(:no_hours_registered, project: project.name)
          .active-people
            - project.users.each do |user|
              = render "application/avatar", user: user, easter: easter?
= paginate projects

app/views/clients/edit.html.haml
.outer
  .container
    %h1= title
    = render partial: "form"

app/views/clients/index.html.haml
.outer
  .container
    %h1= title
    %hr/
    %ul.clients-overview= render partial: "client", collection: @clients
    %hr/
    %h1= t("titles.clients.new")
    = render partial: "form"

app/views/clients/show.html.haml
- content_for :page_title, @client.name

.outer
  .container
    - localized_cache @client do
      .clients
        %header
          = link_to t("client.edit"), edit_client_path(@client)
          %h1
            = client_title(@client)
            \-
            \#{EntryStats.new(@client.hours).total_hours}
            \#{t('tags.show.hours_indication_title', count: EntryStats.new(@client.hours).total_hours)}
          %p
            = @client.description
      = render "/time_span"
      .charts
        = render @time_series.chart, time_series: @time_series
      .charts
        = render "/charts/pie_chart", title: t("charts.hours_per_project"), data: EntryStats.new(@time_series.entries_for_time_span).hours_for_subject_collection(User.all).to_json
        = render "/charts/pie_chart", title: t("charts.hours_per_client"), data: EntryStats.new(@time_series.entries_for_time_span).hours_for_subject_collection(Project.all).to_json
  %ul.clients-projects-overview
    = render "project", projects: @projects