config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(
                    Rails.root.join("config/routes/#{routes_name}.rb")
                  ))
  end
end

class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Hours::Application.routes.draw do
  if Hours.single_tenant_mode?
    root "projects#index"
    draw :subdomain_present
    draw :subdomain_blank
  else
    constraints(SubdomainPresent) do
      root "projects#index", as: :subdomain_root
      draw :subdomain_present
    end

    constraints(SubdomainBlank) do
      root to: "pages#show", id: "landing"
      draw :subdomain_blank
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string           default(""), not null
#  created_at  :datetime
#  updated_at  :datetime
#  slug        :string
#  budget      :integer
#  billable    :boolean          default("false")
#  client_id   :integer
#  archived    :boolean          default("false"), not null
#  description :text
#

class Project < ApplicationRecord
  include Sluggable

  audited allow_mass_assignment: true

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }
  validates_with ClientBillableValidator
  has_many :hours
  has_many :mileages
  has_many :users, -> { distinct }, through: :hours
  has_many :categories, -> { distinct }, through: :hours
  has_many :tags, -> { distinct }, through: :hours
  belongs_to :client, touch: true

  scope :by_last_updated, -> { order("projects.updated_at DESC") }
  scope :by_name, -> { order("lower(name)") }

  scope :are_archived, -> { where(archived: true) }
  scope :unarchived, -> { where(archived: false) }
  scope :billable, -> { where(billable: true) }

  def sorted_categories
    categories.sort_by do |category|
      EntryStats.new(hours, category).percentage_for_subject
    end.reverse
  end

  def label
    name
  end

  def budget_status
    budget - hours.sum(:value) if budget
  end

  def has_billable_entries?
    hours.exists?(billed: false) ||
      mileages.exists?(billed: false)
  end

  private

  def slug_source
    name
  end
end

app/controllers/projects_controller.rb
include TimeSeriesInitializer

class ProjectsController < ApplicationController
  def index
    @projects = Project.unarchived.by_last_updated.page(params[:page]).per(7)
    @hours_entry = Hour.new
    @mileages_entry = Mileage.new
    @activities = Hour.by_last_created_at.limit(30)
  end

  def show
    @time_series = time_series_for(resource)
  end

  def edit
    resource
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_path, notice: t(:project_created)
    else
      render action: "new"
    end
  end

  def update
    if resource.update_attributes(project_params)
      redirect_to project_path(resource), notice: t(:project_updated)
    else
      render action: "edit"
    end
  end

  private

  def entry_type
    request.fullpath == mileage_entry_path ? "mileages" : "hours"
  end

  def resource
    @project ||= Project.find_by_slug(params[:id])
  end

  def project_params
    params.require(:project)
          .permit(:name, :billable, :client_id, :archived, :description, :budget)
  end
end

app/views/projects/_categories_bar.html.haml
%span.activity-color{:itemprop => "keywords", :style => "width:#{EntryStats.new(project.hours, category).percentage_for_subject}%; background-color:#{category.name.pastel_color};"}

app/views/projects/_category.html.haml
%li
  .category
    %span.color{:style => "background-color:#{category.name.pastel_color};"}
    %span.activity= category.name
  .spent
    %canvas.spent-chart{"data-color" => category.name.pastel_color, "data-spent" => EntryStats.new(project.hours, category).percentage_for_subject, :height => "100", :width => "100"}
    .spent-info
      %span.hours{:style => "color: #{category.name.pastel_color}"}
        = EntryStats.new(project.hours, category).hours_for_subject
      %span.percent
        = EntryStats.new(project.hours, category).percentage_for_subject
        \%

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name, required: true
    = f.input :description, as: :text, input_html: { rows: 5 }
    = f.input :budget, as: :integer
    = f.association :client, required: false, collection: Client.by_name, placeholder: t("project.form.client"), include_blank: t("project.form.no_client")
    = f.label :billable
    = f.input :billable, as: :switch, label: false
    = f.button :submit, data: { disable_with: t("loader.saving") }
    
    - if !@project.audits.empty?
      = link_to project_audits_path(@project), class: "audit-link" do
        = t("project.show.changes_link")

app/views/projects/_project.html.haml
- projects.each do |project|
  - localized_cache [project, current_locale] do
    - present project do |project_presenter|
      %li.container.project
        %h2.project-title
          = link_to project_path(project) do
            = project.name
        %ul.tags-list
          - project.tags.last(5).each do |tag|
            = link_to tag_path(tag) do
              %li.tag= tag.name
        - if project.client
          = link_to client_path(project.client), class: "clients-header" do
            = client_title(project.client)
        - if project.budget
          .project-budget
            = t(:budget_html, budget_left: project.budget_status, budget: project.budget)
        %hr/
        .activities-overview
          %ol.activities
            = project_presenter.show_categories
        .bar
          .graph
            = project_presenter.show_categories_bar
        .activity-description
          - if project.users.count > 0
            = t(:project_activity_html, full_name: project.users.first.full_name, count: project.users.count, hours: EntryStats.new(project.hours).total_hours, project: project.name)
          - else
            = t(:no_hours_registered, project: project.name)
          .active-people
            - project.users.each do |user|
              = render "application/avatar", user: user, easter: easter?
= paginate projects

app/views/projects/_project_detail.html.haml
- present project do |project_presenter|
  .project
    %header
      %div.actions
        %div
          = link_to edit_project_path(project) do
            = t("project.show.edit_link")
      = link_to project_path(project) do
        %h2= project.name
      - if project.client
        = link_to client_path(project.client), class: "clients-header" do
          = client_title(project.client)
      - if project.budget
        .project-budget
          = t(:budget_html, budget_left: project.budget_status, budget: project.budget)
      %p= markdown(project.description) if project.description
    %hr/
  .activities-overview
    %ol.activities
      = project_presenter.show_categories
  %br/
  .bar
    .graph
      = project_presenter.show_categories_bar
  .activity-description
    - if project.users.count > 0
      = t(:project_activity_html, full_name: project.users.first.full_name, count: project.users.count, hours: EntryStats.new(project.hours).total_hours, project: project.name)
    - else
      = t(:no_hours_registered, project: project.name)
    .active-people.hide-for-mobile
      - project.users.each do |user|
        = render "application/avatar", user: user, easter: easter?

app/views/projects/edit.html.haml
.outer
  .container
    - if @project.archived?
      = link_to t("project.edit.un_archive_link"), project_path(@project, project: { archived: false }), method: "put", class: "archive-link"
    - else
      = link_to t("project.edit.archive_link"), project_path(@project, project: { archived: true }), method: "put", class: "archive-link"
    %h1= title
    = render partial: "form"

app/views/projects/index.html.haml
.outer
  .wrapper
    .projects-overview
      .new-entry-wrapper
        %h2= t("entries.index.new")
        .projects-tabs-container
          %ul.accordion-tabs
            %li.tab-header-and-content-left
              %a.tab-link{href: "#hours"}= t("entries.index.hours")
              #hours-tab.tab-content
                %table.entries-table
                  = render partial: "application/hours_entry_form", locals: { form_title: t("entries.index.new_hours")  }
            %li.tab-header-and-content-right
              %a.tab-link{href: "#mileages"}= t("entries.index.mileages")
              #mileages-tab.tab-content
                %table.entries-table
                  = render partial: "application/mileages_entry_form", locals: { form_title: t("entries.index.new_mileages") }
      %ul.project-list
        - localized_cache cache_keys_for_all(:projects, :categories) do
          - unless Project.any?
            .info
              %p= t("info.no_projects_html", new_project_path: link_to(t("info.here"), new_project_path))
          - unless Category.any?
            .info
              %p= t("info.no_categories_html", categories_path: link_to(t("info.here"), categories_path))
          = render partial: "project", locals: { projects: @projects }
      .new-project
        = link_to t("titles.projects.new"), new_project_path, id: "new-project-button", class: "button create"
    .activity-feed
      %ul
        - localized_cache [cache_key_for_all(:hours), current_locale] do
          = render partial: "entry", collection: @activities

app/views/projects/new.html.haml
.outer
  .container
    %h1= title
    = render partial: "form"

app/views/projects/show.html.haml
- content_for :page_title, @project.name

- localized_cache [@project, params[:time_span]] do
  .outer
    .container
      = render partial: "project_detail", locals: { project: @project }
      = render "/time_span"
      .charts
        = render @time_series.chart, time_series: @time_series
      .charts
        = render "/charts/pie_chart", title: t('charts.hours_spent_per_user'), data: EntryStats.new(@time_series.entries_for_time_span).hours_for_subject_collection(User.all).to_json
        = render "/charts/pie_chart", title: t('charts.hours_spent_per_category'), data: EntryStats.new(@time_series.entries_for_time_span).hours_for_subject_collection(Category.all).to_json
      %table
        %tbody
          %tr
            %th= t('project.table_head.tag')
            %th= t('project.table_head.hours')
          - @project.tags.each do |tag|
            %tr
              %td= link_to tag.name, tag_path(tag)
              %td= EntryStats.new(tag.hours, @project).hours_for_subject